[book]
authors = ["Jason McNeil"]
language = "en"
multilingual = false
src = "src"
title = "Example"

[preprocessor.nix-eval]
command = "../target/release/mdbook-nix-eval"
renderer = ["html"]
#eval_command = "nix-instantiate"
eval_args = "--timeout 5"
